export const LOAI_DAT = {
  // Nhóm đất nông nghiệp
  LUC: "Đất chuyên trồng lúa nước",
  LUK: "Đất trồng lúa nước còn lại",
  LUA: "Đất trồng lúa",
  BHK: "Đất trồng cây hàng năm khác",
  NHK: "Đất trồng cây hàng năm khác",
  CLN: "Đất trồng cây lâu năm",
  RSX: "Đất rừng sản xuất",
  RPH: "Đất rừng phòng hộ",
  RDD: "Đất rừng đặc dụng",
  NTS: "Đất nuôi trồng thủy sản",
  LMU: "Đất làm muối",
  NKH: "Đất nông nghiệp khác",
  HNK: "Đất trồng cây hàng năm khác",
  ONT: "Đất ở tại nông thôn",
  ODT: "Đất ở tại đô thị",
  TSC: "Đất xây dựng trụ sở cơ quan",
  DTS: "Đất xây dựng trụ sở của tổ chức sự nghiệp",
  DVH: "Đất xây dựng cơ sở văn hóa",
  DYT: "Đất xây dựng cơ sở y tế",
  DGD: "Đất xây dựng cơ sở giáo dục và đào tạo",
  DTT: "Đất xây dựng cơ sở thể dục thể thao",
  DKH: "Đất xây dựng cơ sở khoa học và công nghệ",
  DXH: "Đất xây dựng cơ sở dịch vụ xã hội",
  DNG: "Đất xây dựng cơ sở ngoại giao",
  DSK: "Đất xây dựng công trình sự nghiệp khác",
  CQP: "Đất quốc phòng",
  CAN: "Đất an ninh",
  SKK: "Đất khu công nghiệp",
  SKT: "Đất khu chế xuất",
  SKN: "Đất cụm công nghiệp",
  SKC: "Đất cơ sở sản xuất phi nông nghiệp",
  TMD: "Đất thương mại, dịch vụ",
  SKS: "Đất sử dụng cho hoạt động khoáng sản",
  SKX: "Đất sản xuất vật liệu xây dựng, làm đồ gốm",
  DGT: "Đất giao thông",
  DTL: "Đất thủy lợi",
  DNL: "Đất công trình năng lượng",
  DBV: "Đất công trình bưu chính, viễn thông",
  DSH: "Đất sinh hoạt cộng đồng",
  DKV: "Đất khu vui chơi, giải trí công cộng",
  DCH: "Đất chợ",
  DDT: "Đất có di tích lịch sử, văn hóa",
  DDL: "Đất có danh lam thắng cảnh",
  DRA: "Đất bãi thải, xử lý chất thải",
  DCK: "Đất công trình công cộng khác",
  TON: "Đất cơ sở tôn giáo",
  TIN: "Đất cơ sở tín ngưỡng",
  NTD: "Đất làm nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng",
  SON: "Đất sông, ngòi, kênh, rạch, suối",
  MNC: "Đất có mặt nước chuyên dùng",
  PNK: "Đất phi nông nghiệp khác",
  // Nhóm đất chưa sử dụng
  BCS: "Đất bằng chưa sử dụng",
  DCS: "Đất đồi núi chưa sử dụng",
  NCS: "Núi đá không có rừng cây",
};

export const GIAY_TO = {
  CMND: "Chứng minh nhân dân",
  CCCD: "Căn cước công dân",
};
